
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JATIN
 */
public class Mark11th extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;
    /**
     * Creates new form Mark11th
     */
    public Mark11th() {
        initComponents();
    }
private void filter1(String l)
{
    DefaultTableModel dm=(DefaultTableModel)tb1.getModel();
    TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(dm);  
    tb1.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(l,2));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        b1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        class1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        sec1 = new javax.swing.JTextField();
        b3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MARK ATTENDANCE 11th");

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        jLabel11.setText("BACK");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Roll no", "Student Name", "Section", "Present "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb1);

        b1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b1.setText("MARK ATTENDANCE");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        c1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("STUDENT NAME");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("CLASS");

        class1.setEditable(false);
        class1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        class1.setText("11");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("SECTION");

        c2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c2ItemStateChanged(evt);
            }
        });

        sec1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setText("SELECT ALL");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("DESELECT ALL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("REFRESH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("STUDENT REGISTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        t1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("SEARCH FIELD");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATE");

        d1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

   try{
            Date d=new Date();
            int y=d.getYear()+1900;
            int mon=d.getMonth()+1;
            int da=d.getDate();
            String a;
            String check="11std"+y;
            Class.forName("java.sql.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
            stmt=con.createStatement();
            String sql2="show databases like '11std"+y+"';";
            rs=stmt.executeQuery(sql2);
            System.out.println(sql2);
            if(rs.next()){
                a=rs.getString(1);
                System.out.println(a);
                if(a.equals("11std"+y))
                {String sql="SELECT count(*) FROM information_schema.TABLES WHERE (TABLE_SCHEMA = '11std"+y+"') AND (TABLE_NAME = '"+mon+"m');";
                    rs=stmt.executeQuery(sql);
                    System.out.println(sql);
                    rs.next();
                    int b=rs.getInt(1);
                    System.out.println(b);
                    int daycount;
                    if(b==1)
                    {con=DriverManager.getConnection("jdbc:mysql://localhost/11std"+y, "root", "1234");
                        stmt=con.createStatement();
                        if( mon==1 || mon==3 || mon==5 || mon==7 || mon==8 || mon==10 || mon==12 )
                        {
                            daycount=31;
                        }
                        else if( mon==4 || mon==6 || mon==9 || mon==11  )
                        {
                            daycount=30;
                        }
                        else
                        {
                            daycount=28;
                        }
                        String quer1="SELECT * FROM "+mon+"m;";
                        Statement st1=con.createStatement();
                        ResultSet rs1=st1.executeQuery(quer1);
                        System.out.println(quer1);
                        System.out.println(daycount);
                        ResultSetMetaData rsmd1 = rs1.getMetaData();
                        int ncol1=1;
                        ncol1=rsmd1.getColumnCount();
                        if (ncol1 == 34 || ncol1 == 33 || ncol1 == 31) {
                            System.out.println("YOOOOOOOOOOOOOOO");
                        }
                        else
                        {
                             for (int i = 1; i <= daycount; i++) {
                                String sql4 = "Alter table " + mon + "m Add Column " + i + "d int DEFAULT -1";
                                stmt.executeUpdate(sql4);
                                System.out.println(sql4);
                            }
                        }
                        DefaultTableModel tm=(DefaultTableModel)tb1.getModel();
                        int rows=tb1.getRowCount();
                        stmt=con.createStatement();
                        String quer="SELECT * FROM "+mon+"m;";
                        Statement st=con.createStatement();
                        ResultSet rs=st.executeQuery(quer);
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int ncol=0;
                        ncol=rsmd.getColumnCount();
                        if(ncol==3){
                            for(int row=0;row<rows;row++){
                                String id=(String) tb1.getValueAt(row,0);
                                String roll =(String) tb1.getValueAt(row, 1);
                                String sname=(String) tb1.getValueAt(row, 2);
                                String sec=(String) tm.getValueAt(row, 3);
                                boolean pre=(boolean) tm.getValueAt(row, 4);
                                int c;
                                if(pre==true)
                                c=1;
                                else
                                c=0;
                                String sql5 = "INSERT INTO "+mon+"m(Rollno,StudentName,Section) VALUES("+roll+",'"+sname+"','"+sec+"');";
                                stmt.executeUpdate(sql5);
                            }
                        }
                        else if(ncol>3){
                            DefaultTableModel tm1=(DefaultTableModel)tb1.getModel();
                            int rows1=tb1.getRowCount();
                            String sqlrows="Select count(rollno) from "+mon+"m;";
                            rs=stmt.executeQuery(sqlrows);
                            rs.next();
                            int sqlrowsno=rs.getInt(1);
                            System.out.println("no of rows of sql table "+sqlrowsno);
                            System.out.println("no of rows of jtable "+rows1);
                            int difference=rows-sqlrowsno;
                            System.out.println(difference+" difference of rows in sql and table");
                            if(difference>0)
                            {System.out.println("h");
                                for(int row=sqlrowsno;row<rows1;row++)
                                {String id=(String) tb1.getValueAt(row,0);
                                String roll =(String) tb1.getValueAt(row, 1);
                                String sname=(String) tb1.getValueAt(row, 2);
                                String sec=(String) tm.getValueAt(row, 3);
                                boolean pre=(boolean) tm.getValueAt(row, 4);
                                int c;
                                if(pre==true)
                                c=1;
                                else
                                c=0;
                                    String addnewnametotable="INSERT INTO "+mon+"m(Rollno,StudentName,Section) VALUES("+roll+",'"+sname+"','"+sec+"');";
                                    stmt.executeUpdate(addnewnametotable);
                                }
                            }
                            for(int row=0;row<rows1;row++){
                                String id=(String) tb1.getValueAt(row,0);
                                String roll =(String) tb1.getValueAt(row, 1);
                                String sname=(String) tb1.getValueAt(row, 2);
                                String sec=(String) tm.getValueAt(row, 3);
                                boolean pre=(boolean) tm.getValueAt(row, 4);
                                int c;
                                if(pre==true)
                                c=1;
                                else
                                c=0;
                                String sql99="Update "+mon+"m  Set "+da+"d="+c+" where StudentName='"+sname+"';";
                                stmt.executeUpdate(sql99);
                                System.out.println(sql99);
                            }
                        }
                        JOptionPane.showMessageDialog(null,"Attendance Marked");

                    }
                    else if(b==0)
                    {con=DriverManager.getConnection("jdbc:mysql://localhost/11std"+y, "root", "1234");
                        stmt=con.createStatement();
                        String sql6="Create table "+mon+"m (Rollno int,StudentNAme varchar(48),Section varchar(3));";
                        stmt.executeUpdate(sql6);
                        if( mon==1 || mon==3 || mon==5 || mon==7 || mon==8 || mon==10 || mon==12 )
                        {
                            daycount=31;
                        }
                        else if( mon==4 || mon==6 || mon==9 || mon==11  )
                        {
                            daycount=30;
                        }
                        else
                        {
                            daycount=28;
                        }
                        String quer1="SELECT * FROM "+mon+"m;";
                        Statement st1=con.createStatement();
                        ResultSet rs1=st1.executeQuery(quer1);
                        System.out.println(quer1);
                        System.out.println(daycount);
                        ResultSetMetaData rsmd1 = rs1.getMetaData();
                        int ncol1=1;
                        ncol1=rsmd1.getColumnCount();
                        if (ncol1 == 34 || ncol1 == 33 || ncol1 == 31) {
                            System.out.println("YOOOOOOOOOOOOOOO");
                        }
                        else
                        {
                             for (int i = 1; i <= daycount; i++) {
                                String sql4 = "Alter table " + mon + "m Add Column " + i + "d int DEFAULT -1";
                                stmt.executeUpdate(sql4);
                                System.out.println(sql4);
                            }
                        }
                        DefaultTableModel tm=(DefaultTableModel)tb1.getModel();
                        stmt=con.createStatement();
                        String quer="SELECT * FROM "+mon+"m;";
                        Statement st=con.createStatement();
                        ResultSet rs=st.executeQuery(quer);
                        ResultSetMetaData rsmd = rs.getMetaData();
                        int ncol=0;
                        ncol=rsmd.getColumnCount();
                        int rows=tb1.getRowCount();
                        System.out.println(ncol);
                        if(ncol>=3){
                            for(int row=0;row<rows;row++){
                                String id=(String) tb1.getValueAt(row,0);
                                String roll =(String) tb1.getValueAt(row, 1);
                                String sname=(String) tb1.getValueAt(row, 2);
                                String sec=(String) tm.getValueAt(row, 3);
                                boolean pre=(boolean) tm.getValueAt(row, 4);
                                int c;
                                if(pre==true)
                                c=1;
                                else
                                c=0;
                                String sql5 = "INSERT INTO "+mon+"m(Rollno,StudentName,Section) VALUES("+roll+",'"+sname+"','"+sec+"');";
                                stmt.executeUpdate(sql5);
                                System.out.println(sql5);
                            }
                        }
                        if(ncol>3){
                            DefaultTableModel tm1=(DefaultTableModel)tb1.getModel();
                            int rows1=tb1.getRowCount();
                            for(int row=0;row<rows1;row++){
                                String id=(String) tb1.getValueAt(row,0);
                                String roll =(String) tb1.getValueAt(row, 1);
                                String sname=(String) tb1.getValueAt(row, 2);
                                String sec=(String) tm.getValueAt(row, 3);
                                boolean pre=(boolean) tm.getValueAt(row, 4);
                                int c;
                                if(pre==true)
                                c=1;
                                else
                                c=0;
                                String sql99="Update "+mon+"m  Set "+da+"d="+c+" where StudentName='"+sname+"';";
                                stmt.executeUpdate(sql99);
                                System.out.println(sql99);
                            }
                            JOptionPane.showMessageDialog(null,"Attendance Marked");
                        }
                    }
                }
            }
            else
            {   con=DriverManager.getConnection("jdbc:mysql://localhost/jatin","root","1234");
                stmt=con.createStatement();
                String sql7="Create database 11std"+y;
                stmt.executeUpdate(sql7);
                System.out.println(sql7);
                con=DriverManager.getConnection("jdbc:mysql://localhost/11std"+y, "root", "1234");
                stmt=con.createStatement();
                String sql6="Create table "+mon+"m (Rollno int,StudentNAme varchar(490),Section varchar(3));";
                stmt.executeUpdate(sql6);
                System.out.println(sql6);
                int daycount;
                 if( mon==1 || mon==3 || mon==5 || mon==7 || mon==8 || mon==10 || mon==12 )
                        {
                            daycount=31;
                        }
                        else if( mon==4 || mon==6 || mon==9 || mon==11  )
                        {
                            daycount=30;
                        }
                        else
                        {
                            daycount=28;
                        }
                        String quer1="SELECT * FROM "+mon+"m;";
                        Statement st1=con.createStatement();
                        ResultSet rs1=st1.executeQuery(quer1);
                        System.out.println(quer1);
                        System.out.println(daycount);
                        ResultSetMetaData rsmd1 = rs1.getMetaData();
                        int ncol1=1;
                        ncol1=rsmd1.getColumnCount();
                        if (ncol1 == 34 || ncol1 == 33 || ncol1 == 31) {
                            System.out.println("YOOOOOOOOOOOOOOO");
                        }
                        else
                        {
                             for (int i = 1; i <= daycount; i++) {
                                String sql4 = "Alter table " + mon + "m Add Column " + i + "d int DEFAULT -1";
                                stmt.executeUpdate(sql4);
                                System.out.println(sql4);
                            }
                        }
                DefaultTableModel tm=(DefaultTableModel)tb1.getModel();
                int rows=tb1.getRowCount();
                stmt=con.createStatement();
                String quer="SELECT * FROM "+mon+"m;";
                Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(quer);
                ResultSetMetaData rsmd = rs.getMetaData();
                int ncol=0;
                
                ncol=rsmd.getColumnCount();
                if(ncol>=3){
                    for(int row=0;row<rows;row++){
                        String id=(String) tb1.getValueAt(row,0);
                        String roll =(String) tb1.getValueAt(row, 1);
                        String sname=(String) tb1.getValueAt(row, 2);
                        String sec=(String) tm.getValueAt(row, 3);
                        boolean pre=(boolean) tm.getValueAt(row, 4);
                        int c;
                        if(pre==true)
                        c=1;
                        else
                        c=0;
                        String sql5 = "INSERT INTO "+mon+"m(Rollno,StudentName,Section) VALUES("+roll+",'"+sname+"','"+sec+"');";
                        stmt.executeUpdate(sql5);
                    }
                    JOptionPane.showMessageDialog(null,"Attendance Marked");
                }
                 if(ncol>3){
                    DefaultTableModel tm1=(DefaultTableModel)tb1.getModel();
                    int rows1=tb1.getRowCount();
                    for(int row=0;row<rows1;row++){
                        String id=(String) tb1.getValueAt(row,0);
                        String roll =(String) tb1.getValueAt(row, 1);
                        String sname=(String) tb1.getValueAt(row, 2);
                        String sec=(String) tm.getValueAt(row, 3);
                        boolean pre=(boolean) tm.getValueAt(row, 4);
                        int c;
                        if(pre==true)
                        c=1;
                        else
                        c=0;
                        String sql99="Update "+mon+"m  Set "+da+"d="+c+" where StudentName='"+sname+"';";
                        stmt.executeUpdate(sql99);
                    }
                    JOptionPane.showMessageDialog(null,"Attendance Marked");
                }
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
            MainPage mn= new MainPage();
            mn.setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_c1ItemStateChanged

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
        try
        {c2.removeAllItems();
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
            stmt=con.createStatement();
            int b=Integer.parseInt(c1.getSelectedItem().toString());
            String sql1="Select StudentName from studentrgstr where ID="+b+";";
            rs=stmt.executeQuery(sql1);
            System.out.println(sql1);
            while(rs.next())
            {
                String sname=rs.getString(1);
                c2.addItem(sname);
            }
            int a=Integer.parseInt(c1.getSelectedItem().toString());
            String sql3="Select * from batchrgstr where ID="+a+";";
            System.out.println(sql3);
            rs=stmt.executeQuery(sql3);

            while(rs.next())
            {
                String sec=rs.getString(6);
                String cclass=rs.getString(4);
                sec1.setText(sec);
                class1.setText(cclass);
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_c1FocusLost

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c2ItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_c2ItemStateChanged

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        for (int i = 0; i < tb1.getRowCount(); i++) {
            tb1.setValueAt(true,i, 4);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 0; i < tb1.getRowCount(); i++) {
            tb1.setValueAt(false,i, 4);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        this.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        StudentRegistration sg=new StudentRegistration();
        this.dispose();
        sg.setVisible(true);
        sg.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyPressed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
        String s=t1.getText();
        filter1(s);
        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
Mark12th nf=new  Mark12th();
nf.setLocationRelativeTo(this);
        try{
 c1.removeAllItems();
 c2.removeAllItems();
 Class.forName("com.mysql.jdbc.Driver");
 con = DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
 stmt=con.createStatement();
 String sql="Select distinct ID from studentrgstr where Class=11;";
 rs=stmt.executeQuery(sql);
    System.out.println(sql);
 while(rs.next())
 {
    int a=rs.getInt(1);
    c1.addItem(""+a); 
    
 }
 
 String sql2="Select * from studentrgstr where Class=11;";
            System.out.println(sql2);
            DefaultTableModel tm=(DefaultTableModel)tb1.getModel();
            tm.setRowCount(0);
            ResultSet rs=stmt.executeQuery(sql2);
            while(rs.next())
            {  
               String sname2=rs.getString(2);
               int id2=rs.getInt(3);
               String batchcode4=rs.getString(4);
               String se=rs.getString(5);
               int rol=rs.getInt(1);
               tm.addRow(new Object[]{""+id2,""+rol,sname2,se,true});
            }
 
    
 int b=Integer.parseInt(c1.getSelectedItem().toString());
String sq="Select Class,Section from batchrgstr where ID="+b+";";
rs=stmt.executeQuery(sq);
    System.out.println(sq);
while(rs.next())
{
 String s=rs.getString(1);
 class1.setText(s);
 String s1=rs.getString(2);
 sec1.setText(s1);
}
String sql1="Select StudentName from studentrgstr where Class=11";
    System.out.println(sql1);
rs=stmt.executeQuery(sql1);
while(rs.next())
{
    String sname=rs.getString(1);
    c2.addItem(sname);
}
String sql3="Select curdate()";
            System.out.println(sql3);
            rs=stmt.executeQuery(sql3);
            rs.next();
            Date f=rs.getDate(1);
            d1.setText(""+f);
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null, e.getMessage()+"Empty");
            MainPage mn=new MainPage();
            this.dispose();
            mn.setVisible(true);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        MainPage mn=new MainPage();
        mn.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

     private void filter(String lol)
  {DefaultTableModel dm=(DefaultTableModel)tb1.getModel();
    TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(dm);  
    tb1.setRowSorter(tr);
    if(lol!="")
    {
        tr.setRowFilter(RowFilter.regexFilter(lol));
    }
    else{
        tb1.setRowSorter(tr);
    }
        
  }
 public boolean checkColumn(String column,String month)
{ 
 PreparedStatement ps;
 ResultSet rs;
 boolean checkCol = false;
 String query = " Select count(*) From Information_Schema.Columns Where Table_name='?' and Column_name='?';";
 try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,month);
            ps.setString(2,column);            
            rs = ps.executeQuery();
            rs.next();
            int a=rs.getInt(1);
            if(a>=1){
            checkCol = true;
            }
            else{
                checkCol=false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
         return checkCol;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mark11th.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mark11th.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mark11th.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mark11th.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mark11th().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b3;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JTextField class1;
    private javax.swing.JLabel d1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sec1;
    private javax.swing.JTextField t1;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
