import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JATIN
 */
public class StudentRegistration extends javax.swing.JFrame {
Connection con;
Statement stmt;
ResultSet rs;



    /**
     * Creates new form StudentRegistration
     */
    public StudentRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        b6 = new javax.swing.JButton();
        class1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sec1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btchcode = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rollno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT REGISTRATION");

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Batch Code", "Rollno", "Student Name", "Class", "Section"
            }
        ));
        tb1.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jScrollPane1.setViewportView(tb1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setText("CLASS");

        b6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b6.setText("REGISTER");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        class1.setEditable(false);
        class1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        class1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                class1FocusLost(evt);
            }
        });
        class1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                class1KeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 255));
        jLabel14.setText("SECTION");

        sec1.setEditable(false);
        sec1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sec1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                sec1FocusLost(evt);
            }
        });
        sec1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sec1KeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 255));
        jLabel12.setText("BATCH CODE");

        btchcode.setEditable(false);
        btchcode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btchcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btchcodeFocusLost(evt);
            }
        });
        btchcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btchcodeKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("ROLL NO");

        rollno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rollno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rollnoFocusLost(evt);
            }
        });
        rollno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rollnoKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 255));
        jLabel13.setText("STUDENT NAME");

        sname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                snameFocusLost(evt);
            }
        });
        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                snameKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("ID");

        c1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("IMPORT EXCEL FILE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(43, 43, 43)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btchcode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sec1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(class1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
try{
    
 c1.removeAllItems();
 Class.forName("com.mysql.jdbc.Driver");
 con = DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
 stmt=con.createStatement();
 String sql="Select * from batchrgstr;";
 rs=stmt.executeQuery(sql);
 while(rs.next())
 {
    int a=rs.getInt(7);
    c1.addItem(""+a);  
 }
int b=Integer.parseInt(c1.getSelectedItem().toString());
String sq="Select batchcode from batchrgstr where ID="+b+";";
rs=stmt.executeQuery(sq);
while(rs.next())
{
 String s=rs.getString(1);
 btchcode.setText(s);
}
String sql2="Select * from studentrgstr ;";
            System.out.println(sql2);
            DefaultTableModel tm=(DefaultTableModel)tb1.getModel();
            tm.setRowCount(0);
            ResultSet rs=stmt.executeQuery(sql2);
            while(rs.next())
            {  int rolln=rs.getInt(1);
               String sname2=rs.getString(2);
               int id2=rs.getInt(3);
               String batchcode4=rs.getString(4);
               String sec=rs.getString(5);
               int p=rs.getInt(6);
               tm.addRow(new Object[]{""+id2,batchcode4,""+rolln,sname2,""+p,sec});
                
            }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        MainPage mn=new MainPage();
        mn.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        int i = 0;
        try{ 
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
            stmt=con.createStatement();                   
            String a1=sec1.getText();
            int r=Integer.parseInt(class1.getText());
            String sql6="Select Rollno from studentrgstr where Section='"+a1+"' and Class="+r+";";
            rs=stmt.executeQuery(sql6);
            while(rs.next())
            {
                i=rs.getInt(1);
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        System.out.println("yo");
        int op=Integer.parseInt(rollno.getText());
        if(i==op)
        {
            JOptionPane.showMessageDialog(null,"Roll no "+op+" already exists for Section "+sec1.getText()+" and Class "+class1.getText());
        }
        else if(sname.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter student name");
        }
        else if(rollno.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter rollno");
        }
        
        else{  String a=c1.getSelectedItem().toString();
            try{
                String rol=rollno.getText();
                String sname1=sname.getText();
                String batchcode1=btchcode.getText();
                int b=Integer.parseInt(c1.getSelectedItem().toString());
                DefaultTableModel tm=(DefaultTableModel)tb1.getModel();
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
                stmt=con.createStatement();
                String sql4="Select Section,Class from batchrgstr where ID="+b+";";
                rs=stmt.executeQuery(sql4);
                rs.next();
                String sec=rs.getString(1);
                int d=rs.getInt(2);
                String classs=""+d;

                String sql="INSERT INTO studentrgstr(Rollno,StudentName,ID,batchcode,Section,Class) VALUES('"+rol+"','"+sname1+"',"+a+",'"+batchcode1+"','"+sec+"',"+d+");";
                System.out.println(sql);
                PreparedStatement ps;
                ps = MyConnection.getConnection().prepareStatement(sql);
                int c=ps.executeUpdate(sql);
                System.out.println(a);
                if(c > 0)
                {
                    JOptionPane.showMessageDialog(null,"Student Added");
                    DefaultTableModel tm1=(DefaultTableModel)tb1.getModel();
                    tm.setRowCount(0);
                    Class.forName("java.sql.Driver");
                    Connection con1=DriverManager.getConnection("jdbc:mysql://localhost/jatin","root","1234");
                    Statement st=con.createStatement();
                    String sql1="Select * from studentrgstr;";
                    System.out.println(sql1);
                    ResultSet rs=st.executeQuery(sql1);
                    while(rs.next())
                    {
                        int rolln=rs.getInt(1);
                        String sname2=rs.getString(2);
                        int id2=rs.getInt(3);
                        String batchcode4=rs.getString(4);
                        tm.addRow(new Object[]{""+id2,batchcode4,""+rolln,sname2});

                    }
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void class1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_class1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_class1FocusLost

    private void class1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_class1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_class1KeyPressed

    private void sec1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sec1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_sec1FocusLost

    private void sec1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sec1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sec1KeyPressed

    private void btchcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btchcodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btchcodeFocusLost

    private void btchcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btchcodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btchcodeKeyPressed

    private void rollnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollnoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoFocusLost

    private void rollnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollnoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoKeyPressed

    private void snameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_snameFocusLost

    private void snameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameKeyPressed

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
        try{
            sname.setText("");
            rollno.setText("");
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
            stmt=con.createStatement();
            int b=Integer.parseInt(c1.getSelectedItem().toString());
            String sq="Select * from batchrgstr where ID="+b+";";
            rs=stmt.executeQuery(sq);
            while(rs.next())
            {
                String s=rs.getString(1);
                btchcode.setText(s);
                String sec2=rs.getString(6);
                int dl=rs.getInt(4);
                sec1.setText(sec2);
                class1.setText(""+dl);

            }
            String classs=class1.getText();
            String secc=sec1.getText();
            String sql2="Select * from studentrgstr where Class="+classs+" and Section='"+secc+"';";

        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_c1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
UpdateStudent up=new UpdateStudent();
this.dispose();
up.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{int b1=Integer.parseInt(c1.getSelectedItem().toString());
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/jatin", "root", "1234");
            stmt=con.createStatement();
            String sql5="Select Section,Class,Rollno from studentrgstr where ID="+b1+";";
            rs=stmt.executeQuery(sql5);
            while(rs.next()){
                String sec2=rs.getString(1);
                int dl=rs.getInt(2);
                sec1.setText(sec2);
                class1.setText(""+dl);
            }
            
       }
       catch(Exception e)
       {
         JOptionPane.showMessageDialog(null, e.getMessage());
       }
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Excel e=new Excel();
e.setVisible(true);
this.dispose();
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
sname.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ItemStateChanged

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_c1MouseClicked
public boolean checkSection(String class1)
{ 
 PreparedStatement ps;
 ResultSet rs;
 boolean checkSec = false;
 String query = "SELECT Section  FROM `batchrgstr` WHERE `Class` =?";	
 try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, class1);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkSec = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
         return checkSec;
}
public boolean checkRollno(String class1,String Section)
{ 
 PreparedStatement ps;
 ResultSet rs;
 boolean checkRoll = false;
 String query = "SELECT  Rollno  FROM `studentrgstr` WHERE `Class` =? and 'Section'=?";	
 try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, class1);
            ps.setString(2, Section);
            System.out.println(query);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkRoll = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
         return checkRoll;
}
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b6;
    private javax.swing.JTextField btchcode;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JTextField class1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField rollno;
    private javax.swing.JTextField sec1;
    private javax.swing.JTextField sname;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
